taskapp/models.py
import datetime
import os

import itsdangerous
from flask import current_app
try:
    from flask_login import UserMixin
except:
    from flask.ext.login import UserMixin
from sqlalchemy import or_
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime, timedelta

from .extensions import Base
import sqlalchemy as db


class User(Base, UserMixin):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    is_admin = db.Column(db.Boolean(), default=False)
    name = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(100), nullable=False)

    def __init__(self, name, email, plaintext_pass):
        self.name = name
        self.email = email
        self.set_password(plaintext_pass)

    def set_password(self, plaintext_pass):
        self.password = generate_password_hash(plaintext_pass)

    def verify_password(self, plaintext_pass):
        return check_password_hash(self.password, plaintext_pass)

    def __repr__(self):
        return "<User '%s'>" % self.name

    def __str__(self):
        return self.name

    @classmethod
    def from_email(cls, email):
        """Return a user object for a given email."""
        return cls.query.filter(User.email == email).first()

    @classmethod
    def from_name_or_email(cls, name_or_email):
        """Return a user object for a given username or email."""
        return cls.query.filter(or_(User.name == name_or_email, User.email == name_or_email)).first()

    @classmethod
    def authenticate(cls, name_or_email, plaintext_pass):
        """Return a User object given valid credentials.

        The login parameter may be either the username or password.
        None is returned on failure.
        """
        user = cls.from_name_or_email(name_or_email)
        if user and user.verify_password(plaintext_pass):
            return user
        return None

    def get_token(self, tag):
        """Return a token that can be used to validate or reset a user.

        The tag is a plain string that is used as a namespace. It must also be
        passed to from_token."""
        serialzer = itsdangerous.URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
        return serialzer.dumps(self.id, salt=tag)

    @classmethod
    def from_token(cls, token, tag, max_age=None):
        """Given a token, return the user for that token."""
        serialzer = itsdangerous.URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
        try:
            id = serialzer.loads(token, max_age=max_age, salt=tag)
        except itsdangerous.BadData:
            return None
        return cls.query.get(int(id))


class Simulation(Base):
    """
    Database for an individual run of the simulation
    """
    __tablename__ = 'simulation'
    simulation_id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    random_seeding = db.Column(db.Integer, nullable=False)
    input_settings_filename = db.Column(db.Text(), nullable=True)
    output_directory = db.Column(db.Text(), nullable=True)
    start_time = db.Column(db.DateTime, nullable=True)
    end_time = db.Column(db.DateTime, nullable=True)
    has_error = db.Column(db.Boolean, nullable=False)
    node_id = db.Column(db.Text(), nullable=True)
    sub_id = db.Column(db.Integer, db.ForeignKey('submission.sub_id'), nullable=False)
    has_started = db.Column(db.Integer, nullable=False)
    is_complete = db.Column(db.Boolean, nullable=False)
    submission = db.orm.relationship('Submission', foreign_keys=[sub_id])
    user = db.orm.relationship('User', foreign_keys=[user_id])
    _serialize_field = ['simulation_id',
                        'input_settings_filename',
                        'user_id',
                        'start_time',
                        'random_seeding',
                        'output_directory',
                        'is_complete',
                        'has_error',
                        'node_id'
                        ]

    def __init__(self, user_id, sub_id):
        self.user_id = user_id
        self.sub_id = sub_id
        self.has_started = False
        self.has_error = False
        self.is_complete = False

    def serialize(self):

        return_dict = {field_name: getattr(self, field_name) for field_name in self._serialize_field }
        return_dict['submission'] = self.submission.serialize()
        return return_dict


class Submission(Base):
    """
    Database for a submission of a set of simulation runs
    """
    __tablename__ = 'submission'
    sub_id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    submission_time = db.Column(db.DateTime, nullable=False)
    high_level_script_name = db.Column(db.Text(), nullable=False)
    simulation_name = db.Column(db.Text(), nullable=False)
    high_level_script_version = db.Column(db.Float, nullable=False)
    simulation_version = db.Column(db.Float, nullable=False)
    start_time = db.Column(db.DateTime, nullable=True)
    completion_time = db.Column(db.DateTime, nullable=True)
    has_error = db.Column(db.Boolean)
    user = db.orm.relationship('User',foreign_keys=[user_id])

    _states = ('Submitted',
               'Running',
               'Completed',
               'Error')

    _serialize_field = ['high_level_script_name',
                        'simulation_name'
                        ]

    def __init__(self, user_id, hl_name, sim_name, hl_ver, sim_ver):
        self.user_id = user_id
        self.submission_time = datetime.now()
        self.high_level_script_name = hl_name
        self.simulation_name = sim_name
        self.high_level_script_version = hl_ver
        self.simulation_version = sim_ver

    def __repr__(self):
        return "<Model Run # '%s'>" % self.sub_id

    def __str__(self):
        return self.sub_id

    def set_complete(self):
        self.completion_time = datetime.now()

    def get_name(self):
        return self.__repr__()

    def get_state(self):
        if self.has_error:
            return self._states[3]

        if not self.start_time and not self.completion_time:
            return self._states[0]
        elif self.start_time and not self.completion_time:
            return self._states[1]
        elif self.start_time and self.completion_time:
            return self._states[2]

    def serialize(self):
        return_dict = {field_name: getattr(self, field_name) for field_name in self._serialize_field}
        return return_dict

taskapp/api/forms.py
from flask_wtf import Form
from flask_wtf.file import FileField
import wtforms as wtf
from wtforms.validators import InputRequired, NumberRange


class UploadForm(Form):
    script_name = wtf.StringField('Script Name', [InputRequired()])
    script_version = wtf.DecimalField('Script Version', [InputRequired()])
    simulation_name = wtf.StringField('Simulation Name', [InputRequired()])
    simulation_version = wtf.DecimalField('Simulation Version', [InputRequired()])
    file = FileField('Script File', validators=[InputRequired()],
                     description='Script file listing simulations')
    submit_button = wtf.SubmitField('Upload Form')

taskapp/user/forms.py
from flask_wtf import Form
import wtforms as wtf
from wtforms.validators import InputRequired, Email, Length, EqualTo, Regexp

class UpdateProfileForm(Form):
    email = wtf.StringField('Email', [InputRequired(), Email()])
    submit_button = wtf.SubmitField('Update profile')

class UpdatePasswordForm(Form):
    current_password = wtf.PasswordField('Current Password', [InputRequired(), Length(min=5)])
    new_password = wtf.PasswordField('New Password', [InputRequired(), Length(min=5)])
    new_password_repeat = wtf.PasswordField('Confirm new password',
                                    [InputRequired(), EqualTo('new_password', message='Passwords must match')])
    submit_button = wtf.SubmitField('Update password')

taskapp/api/__init__.py
from . import views

taskapp/api/views.py
from flask import Blueprint, render_template, url_for, flash, \
    current_app, jsonify, request, abort, redirect
try:
    from flask_login import current_user, login_required
except:
    from flask.ext.login import current_user, login_required
from . import forms
from taskapp.models import Submission, Simulation, User
from taskapp.extensions import db_session
import numpy
import datetime
from flask_socketio import emit
from .. import app

blueprint = Blueprint('api', __name__, url_prefix='/api', static_folder='../static')


def send_active_jobs():
    app.app_runner.emit('active jobs', {'num_jobs': get_total_active_jobs()}, namespace='/live_connect')


@blueprint.route('/upload', methods=['GET', 'POST'])
@login_required
def upload():
    """Create an embeddable form that will redirect to '/upload'"""
    form = forms.UploadForm()
    if form.validate_on_submit():
        new_sub = Submission(current_user.id,
                             form.script_name.data,
                             form.simulation_name.data,
                             form.script_version.data,
                             form.simulation_version.data)
        db_session.add(new_sub)
        print(form.script_name.data,
                             form.simulation_name.data,
                             form.script_version.data,
                             form.simulation_version.data)
        db_session.commit()

        # Add new job -- This will be replaced by adding jobs based on input file
        new_sim = Simulation(current_user.id, new_sub.sub_id)
        new_sim.input_settings_filename = ''
        new_sim.output_directory = 'test.txt'
        new_sim.random_seeding = numpy.random.randint(low=0, high=100000)
        db_session.add(new_sim)
        db_session.commit()
        send_active_jobs()
        #flash('Submission id {} added.'.format(new_sub.sub_id))
        return redirect(url_for('user.submissions'))
    return render_template('api/upload.html', form=form)


@blueprint.route('/simulations/')
@blueprint.route('/simulations/<int:sub_num>')
@blueprint.route('/simulations/<int:sub_num>/<int:page_num>')
@login_required
def simulations(sub_num=None, page_num=1):
    """Return the simulations for a given user, optionally filtered by submission id"""
    sim = Simulation.query.filter(Simulation.user_id == current_user.id).order_by(Simulation.simulation_id.desc())
    if sub_num is not None:
        sim = sim.filter(Simulation.sub_id == sub_num).order_by(Simulation.simulation_id.desc())

    send_active_jobs()

    return render_template('api/simulations.html', simulations=sim)

@blueprint.route('/all_simulations')
def all_simulations():
    """Return the simulations for a given user, optionally filtered by submission id"""
    sim = Simulation.query.order_by(Simulation.simulation_id.desc())

    send_active_jobs()

    return render_template('api/simulations.html', simulations=sim)


# def stream_template(template_name, **context):
#     app.update_template_context(context)
#     t = app.jinja_env.get_template(template_name)
#     rv = t.stream(context)
#     rv.enable_buffering(5)
#     return rv


@blueprint.route('/submissions')
@blueprint.route('/submissions/<sub_num>')
@blueprint.route('/submissions/<sub_num>/<int:page_num>')
@login_required
def submissions(sub_num=None, page_num=1):
    """Return the submissions for a given user, optionally filtered by submission id"""
    sub = Submission.query.filter(Submission.user_id == current_user.id).order_by(Submission.sub_id.desc())
    if sub_num is not None:
        sub = sub.filter(Submission.sub_id == sub_num).order_by(Submission.sub_id.desc())

    send_active_jobs()
    return render_template('api/submissions.html', submissions=sub)


@blueprint.route('/get_job')
@blueprint.route('/get_job/<int:node_id>')
def get_job(node_id=0):
    sim_val = Simulation.query.filter(Simulation.has_started == False).\
                   order_by(Simulation.simulation_id.asc()).first()
    if sim_val:
        sim_val.has_started = True
        sim_val.node_id = request.args['id']
        db_session.commit()
        return_val = sim_val.serialize()
    else:
        return_val = None

    send_active_jobs()
    return jsonify({'job': return_val})




@blueprint.route('/add_job')
def add_job():
    test_user = User.query.filter(User.name == 'test').one()

    test_sub = Submission.query.filter(Submission.user_id == test_user.id).\
        filter(Submission.high_level_script_name == 'echo').\
        filter(Submission.simulation_name == 'test').first()

    if not test_sub:
        test_sub = Submission(test_user.id, 'echo', 'test', 1, 1)
        db_session.add(test_sub)
        db_session.commit()

    new_sim = Simulation(test_user.id, test_sub.sub_id)
    new_sim.input_settings_filename = ''
    new_sim.output_directory = 'test.txt'
    new_sim.random_seeding = numpy.random.randint(low=0, high=100000)
    db_session.add(new_sim)
    db_session.commit()
    send_active_jobs()
    return ''

@blueprint.route('/add_user')
def add_user():
    user = User.query.filter(User.name == 'test').one_or_none()
    if not user:
        new_user = User('test','test@gmail.com','password')
        print('Adding user {}'.format(new_user.name))

        db_session.add(new_user)
        db_session.commit()
    return ''


def get_total_active_jobs():

    sim_val = Simulation.query.filter(Simulation.has_started == False).count()

    return sim_val

@blueprint.route('/finish_job', methods=['PUT'])
def finish_job():
    if not request.json or not 'result' in request.json:
        abort(400)
    sim_json = request.json.get('result')
    sim = Simulation.query.get(sim_json['simulation_id'])
    sim.start_time = datetime.datetime(*sim_json['start_time'][0:6])
    sim.end_time = datetime.datetime(*sim_json['end_time'][0:6])
    sim.has_error = sim_json['has_error']
    sim.is_complete = sim_json['is_complete']

    db_session.commit()
    send_active_jobs()
    return ''

taskapp/app.py
"""The app module contains the app factory function."""
import os

from flask import Flask, url_for, current_app

from . import extensions
from . import settings
from . import api, user, public
from flask_socketio import SocketIO

app_runner = SocketIO()

@app_runner.on('connect','/live_connect')
def handle_socket_connect():
    print('Connected to socket')

@app_runner.on('disconnect','/live_connect')
def handle_socket_connect():
    print('Disconnected to socket')

@app_runner.on('my event')
def handle_my_event(data):
    print('received data {}'.format(data))


def create_app(config=settings.ProdConfig):
    app = Flask(__name__)
    app.config.from_object(config)
    register_extentions(app)
    register_blueprints(app)

    return app


def register_extentions(app):
    extensions.login_manager.init_app(app)
    extensions.csrf.init_app(app)
    app_runner.init_app(app)

def register_blueprints(app):
    app.register_blueprint(api.views.blueprint)
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(user.views.blueprint)

taskapp/user/__init__.py
from . import views

taskapp/user/views.py
from sqlalchemy.sql import func
from sqlalchemy.orm.exc import NoResultFound
from flask import Blueprint, request, redirect, url_for, current_app, render_template, flash
try:
    from flask_login import current_user, login_required
except:
    from flask.ext.login import current_user, login_required
from ..models import User, Submission, Simulation
from ..extensions import login_manager, db_session
from . import forms

blueprint = Blueprint('user', __name__, static_folder='../static')


@login_manager.user_loader
def load_user(id):
    """Used by Flask-Login to load a User model for a session that's logged in"""
    return User.query.get(int(id))


@blueprint.route('/submission')
@login_required
def submissions():
    #sub = db_session.query(Submission).filter(Submission.user_id == current_user.id)
    #if not sub:
    #    sub = []

    return render_template('user/submissions.html')


@blueprint.route('/coming_soon')
@login_required
def coming_soon():
    return render_template('user/coming_soon.html')


@blueprint.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    profile_form = forms.UpdateProfileForm(prefix='profile_form')
    password_form = forms.UpdatePasswordForm(prefix='password_form')

    if profile_form.validate_on_submit() and profile_form.submit_button.data:
        current_user.email = profile_form.email.data
        db_session.commit()
        flash('Profile updated.', 'success')
    elif password_form.validate_on_submit() and password_form.submit_button.data:
        # Manually clear validation from profile_form, since it wasn't submitted
        profile_form.errors.clear()
        for field in profile_form:
            del field.errors[:]

        current_user.set_password(password_form.new_password.data)
        db_session.commit()
        flash('Password updated.', 'success')

    profile_form.email.data = current_user.email

    return render_template('user/profile.html', profile_form=profile_form, password_form=password_form)

taskapp/templates/layouts/base.html
{% block title %}{% endblock %}

{% block head %}
    <meta charset="utf-8">

    <!-- Disable IE compatability mode -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

{%- endblock %}

{% block styles %}
    <link rel="stylesheet" href={{url_for('static', filename='css/base.css')}}>
    <link rel="stylesheet" href={{url_for('static', filename="css/bootstrap.css" )}}>
{%- endblock %}

{% block content -%}
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid" id="top-nav-bar">
            <div class="navbar-header navbar-brand">
                {%- if current_user.is_authenticated -%}
                    <a href={{url_for('user.submissions')}} >
                {%- else -%}
                    <a href={{url_for('public.index')}} >
                {%- endif -%}
                Simulation Management</a>
            </div>
            <div class="navbar-header navbar-brand" id="connected-status">
                Not Connected
            </div>
            <div class="navbar-header navbar-brand" id="job-status">
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated -%}
                        <li class="active" title="Edit profile"><a href={{url_for('user.profile')}}><span class="glyphicon glyphicon-user"></span> {{ current_user.name }}</a></li>
                        <li title="Log out"><a href={{url_for('public.logout')}}><span class="glyphicon glyphicon-log-out"></span></a></li>
                    {%- else -%}
                        <li><a href={{url_for('public.signup')}}>Sign up</a></li>
                        <li class="active"><a href={{url_for('public.login')}}>Log in</a></li>
                    {%- endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        {% block main -%}
        {%- endblock %}
    </div>
{%- endblock %}


{% block scripts %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.1.0.js') }}"></script>
    <script src={{url_for('static', filename="js/bootstrap.js" )}}></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>

{% endblock %}

taskapp/templates/layouts/macros.html
{% macro show_flash() -%}
    {% with messages = get_flashed_messages(with_categories=true) -%}
        {% if messages -%}
            {% for category, message in messages %}
            <div class="alert alert-{{category}} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
            {% endfor %}
        {%- endif %}
    {%- endwith %}
{%- endmacro %}

{% macro create_table(headers, rows, table_class='') -%}
<table class="{{ table_class }}">
    <thead>
        {% for h in headers %}
        <th>{{ h | title }}</th>
        {% endfor %}
    </thead>
    <tbody class="list">
        {% for row in rows %}
        <tr>
            {% for cell in row -%}
            <td>{{ cell }}</td>
            {% endfor %}
        </tr>
        {%- endfor %}
    </tbody>
</table>
{%- endmacro %}

taskapp/templates/layouts/wtf.html
{# This file is forked from the Flask-Bootstrap version with a patch for a bug
in file input rendering. #}
{% macro form_errors(form, hiddens=True) %}
  {%- if form.errors %}
    {%- for fieldname, errors in form.errors.items() %}
        {%- for error in errors %}
          <p class="error">{{error}}</p>
        {%- endfor %}
    {%- endfor %}
  {%- endif %}
{%- endmacro %}

{% macro _hz_form_wrap(horizontal_columns, form_type, add_group=False) %}
{% if form_type == "horizontal" %}
  {% if add_group %}<div class="form-group">{% endif %}
  <div class="col-{{horizontal_columns[0]}}-offset-{{horizontal_columns[1]}}
              col-{{horizontal_columns[0]}}-{{horizontal_columns[2]}}
             ">
{% endif %}
{{caller()}}

{% if form_type == "horizontal" %}
  {% if add_group %}</div>{% endif %}
  </div>
{% endif %}
{% endmacro %}

{% macro form_field(field,
                    form_type="basic",
                    horizontal_columns=('lg', 2, 10),
                    button_map={}) %}

{# this is a workaround hack for the more straightforward-code of just passing required=required parameter. older versions of wtforms do not have
the necessary fix for required=False attributes, but will also not set the required flag in the first place. we skirt the issue using the code below #}
{% if field.flags.required and not required in kwargs %}
{% set kwargs = dict(required=True, **kwargs) %}
{% endif %}

{% if field.widget.input_type == 'checkbox' %}
  {% call _hz_form_wrap(horizontal_columns, form_type, True) %}
    <div class="checkbox">
      <label>
        {{field()|safe}} {{field.label.text|safe}}
      </label>
    </div>
  {% endcall %}
{%- elif field.type == 'RadioField' -%}
  {# note: A cleaner solution would be rendering depending on the widget,
     this is just a hack for now, until I can think of something better #}
  {% call _hz_form_wrap(horizontal_columns, form_type, True) %}
    {% for item in field -%}
      <div class="radio">
        <label>
          {{item|safe}} {{item.label.text|safe}}
        </label>
      </div>
    {% endfor %}
  {% endcall %}
{%- elif field.type == 'SubmitField' -%}
  {# note: same issue as above - should check widget, not field type #}
  {% call _hz_form_wrap(horizontal_columns, form_type, True) %}
    {{field(class='btn btn-%s' % button_map.get(field.name, 'default'))}}
  {% endcall %}
{%- elif field.type == 'FormField' -%}
{# note: FormFields are tricky to get right and complex setups requiring
   these are probably beyond the scope of what this macro tries to do.
   the code below ensures that things don't break horribly if we run into
   one, but does not try too hard to get things pretty. #}
  <fieldset>
    <legend>{{field.label}}</legend>
    {%- for subfield in field %}
      {% if not bootstrap_is_hidden_field(subfield) -%}
        {{ form_field(subfield,
                      form_type=form_type,
                      horizontal_columns=horizontal_columns,
                      button_map=button_map) }}
      {%- endif %}
    {%- endfor %}
  </fieldset>
{% else -%}
  <div class="form-group {% if field.errors %} has-error{% endif %}">
      {%- if form_type == "inline" %}
        {{field.label(class="sr-only")|safe}}
        {{field(class="form-control", placeholder=field.description, **kwargs)|safe}}
      {% elif form_type == "horizontal" %}
        {{field.label(class="control-label " + (
          " col-%s-%s" % horizontal_columns[0:2]
        ))|safe}}
        <div class=" col-{{horizontal_columns[0]}}-{{horizontal_columns[2]}}">
          {{field(class="form-control", **kwargs)|safe}}
        </div>
        {%- if field.errors %}
          {%- for error in field.errors %}
            {% call _hz_form_wrap(horizontal_columns, form_type) %}
              <p class="help-block">{{error}}</p>
            {% endcall %}
          {%- endfor %}
        {%- elif field.description -%}
          {% call _hz_form_wrap(horizontal_columns, form_type) %}
            <p class="help-block">{{field.description|safe}}</p>
          {% endcall %}
        {%- endif %}
      {%- else -%}
        {{field.label(class="control-label")|safe}}
        {% if field.type == 'FileField' %}
          {{field(**kwargs)|safe}}
        {% else %}
          {{field(class="form-control", **kwargs)|safe}}
        {% endif %}

        {%- if field.errors %}
          {%- for error in field.errors %}
            <p class="help-block">{{error}}</p>
          {%- endfor %}
        {%- elif field.description -%}
          <p class="help-block">{{field.description|safe}}</p>
        {%- endif %}
      {%- endif %}
  </div>
{% endif %}
{% endmacro %}

{# valid form types are "basic", "inline" and "horizontal" #}
{% macro quick_form(form,
                    action="",
                    method="post",
                    extra_classes=None,
                    role="form",
                    form_type="basic",
                    horizontal_columns=('lg', 2, 10),
                    enctype=None,
                    button_map={},
                    id="") %}
<form
  {%- if action %} action="{{action}}"{% endif -%}
  {%- if id %} id="{{id}}"{% endif -%}
  {%- if method %} method="{{method}}"{% endif %}
  class="form
    {%- if extra_classes %} {{extra_classes}}{% endif -%}
    {%- if form_type == "horizontal" %} form-horizontal
    {%- elif form_type == "inline" %} form-inline
    {%- endif -%}
  "
  {%- if enctype %} enctype="{{enctype}}"{% endif -%}
  {%- if role %} role="{{role}}"{% endif -%}
  >
  {{ form.hidden_tag() }}
  {{ form_errors(form, hiddens='only') }}

  {%- for field in form %}
    {% if not False -%}
      {{ form_field(field,
                    form_type=form_type,
                    horizontal_columns=horizontal_columns,
                    button_map=button_map) }}
    {%- endif %}
  {%- endfor %}

</form>
{%- endmacro %}